<?php

/** Dunkkis Web User Interface
  * ==========================
  * 
  * Copyright (c) 2009-2010 Nomovok Ltd
  * This software is licensed under The MIT License. See LICENSE for details.
  */

include_once "ds-db.php";
include_once "includes/config.inc.php";
include_once "ds-validator.php";
include_once "language/en.inc.php";

$sign_in_page = dirname($_SERVER["PHP_SELF"]) . "/demo.php";

/**
 * page_header
 * Generates page header.
 * @return Returns the HTML generated.
 */
function page_header() {
	return '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'."\n".
		'<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb">'."\n".
		'<head>'."\n".
  		'<meta http-equiv="content-type" content="text/html; charset=utf-8" />'."\n".
		'<title>'.DS_STRING_REGISTR_TITLE.'</title>'."\n".
		'<link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />'."\n".
 		'<link rel="stylesheet" href="css/general.css" type="text/css" />'."\n".
 		'<link rel="stylesheet" href="css/menu.css" type="text/css" />'."\n".
 		'<link rel="stylesheet" href="css/mobile_template.css" type="text/css" />'."\n".
		'</head>'."\n";
}

/**
 * ds_registration_form
 * Generates the registration form.
 * @param action: string Form action.
 * @param method: string Form method.
 * @param errors Errors generated by validation.
 * @param email: string User e-mail.
 * @param pwreq: string User password.
 * @param reason: string User reason for account creation.
 * @return Returns the HTML generated.
 *
 * Revised 7.12.2009 by Juha Hytonen - juha.hytonen@nomovok.com
 */
function ds_registration_form($action,$method,$errors,$email,$pwreq,$reason) {
    global $sign_in_page;
	$out = '<body id="bd" class="fs4 FF" > <div id="ja-wrapper"> <div style="width: auto; position: absolute; height: auto; text-align: center; top: 50%; left: 50%; margin-left: -330px; margin-top: -150px; background-color: #FFFFFF; layer-background-color: #FFFFFF;padding: 30px; border: 1px solid lightblue">'."\n";
	$out .= "<table>\n";
	$out .= "\t<tr><td align='left' ><a href=\"http://dunkkis.org/\">".DS_STRING_REGISTR_GOTO_WEBPAGE."</a></td><td>".DS_STRING_REGISTR_ALREADY_HAVE_ACCOUNT." <a href=\"" . $sign_in_page ."\">".DS_STRING_REGISTR_SIGN_IN."</a></td></tr>\n";
	$out .= "\t<tr> <td> <img src=\"images/dunkkis_login_screen.png\" alt=\"".DS_STRING_REGISTR_DUNKKIS_ORG."\" /> </td>\n";
	$out .= "\t<td>\n";
	$out .= "\t\t<form action='$action' method='$method'>\n";

	if ($errors['email'] == 0) $out .= "<table><tr>\n\t\t\t<tr><td valign='top' align='left' colspan='1'><font size='2'>".DS_STRING_REGISTR_EMAIL.": <br/></font><font size='1'>(".DS_STRING_REGISTR_EMAIL_INFO.")</font></td></tr>\n";
	else if ($errors['email'] == 2) $out .= "\t\t\t<table><tr><td valign='top' align='left' colspan='1'><font size='2' color='red'>".DS_STRING_REGISTR_EMAIL_IN_USE." </font></td></tr>\n";
	else $out .= "\t\t\t<table><tr><td valign='top' align='left' colspan='1'><font size='2' color='red'>".DS_STRING_REGISTR_EMAIL_INVALID." </font></td></tr>\n";
	$out .= "\t\t\t<tr><td align='left'><input type='text' name='email' size='26' value='$email'/></td></tr>\n";

	if (!$errors['pwreq']) $out .= "\t\t\t<tr><td align='left' colspan='1'><font size='2'>".DS_STRING_REGISTR_PWD.":</font></td></tr>\n";
	else $out .= "\t\t\t<tr><td align='left' colspan='1'><font size='2' color='red'>".DS_STRING_REGISTR_PWD_TOO_SHORT_OR_ILLEGAL."</font></td></tr>\n";

	$out .= "\t\t\t<tr><td align='left'><input type='password' name='pwreq' size='26' value='$pwreq'/></td></tr>\n";

	if (!$errors['reason']) $out .= "\t\t\t<tr><td align='left' colspan='1'><font size='2'>".DS_STRING_REGISTR_WHY."</font></td></tr>\n";
	else $out .= "\t\t\t<tr><td align='left' colspan='1'><font size='2' color='red'>".DS_STRING_REGISTR_REASON_MUST_CONTAIN."</font></td></tr>\n";

	$out .= "\t\t<tr><td align='left'><textarea name=\"reason\" cols=\"25\" rows=\"1\" >$reason</textarea></td></tr>\n";
   	$out .= "\t\t<tr><td align='center'><input type='submit' name='submit' value=' ".DS_STRING_REGISTR_APPLY_FOR_ACCOUNT_BUTTON." '/></td></tr>\n";
	$out .= "\t\t</table></form></td></tr></table></div></div>\n";

	return($out);
}

/**
 * account_created
 * Generates the page after account creation.
 * @return Returns the HTML generated.
 */
function account_created(){
    global $sign_in_page;
	$out = '<body id="bd" class="fs4 FF" > <div id="ja-wrapper"> <div style="width: auto; position: absolute; height: auto; text-align: center; top: 50%; left: 50%; margin-left: -330px; margin-top: -150px; background-color: #FFFFFF; layer-background-color: #FFFFFF;padding: 30px; border: 1px solid lightblue">'."\n";
	$out .= "<table>\n";
	$out .= "<tr><td align='left' ><a href=\"http://dunkkis.org/\">".DS_STRING_REGISTR_GOTO_WEBPAGE."</a></td><td>".DS_STRING_REGISTR_ALREADY_HAVE_ACCOUNT." <a href=\"".$sign_in_page."\">".DS_STRING_REGISTR_SIGN_IN."</a></td></tr>\n";
	$out .= "<tr> <td> <img src=\"images/dunkkis_login_screen.png\" alt=\"".DS_STRING_REGISTR_DUNKKIS_ORG."\" /> </td>\n";
	$out .= "<td> <font color='blue' size='3'>".DS_STRING_REGISTR_ACC_REQ_SUCC." <br/> ".DS_STRING_REGISTR_YOU_WILL_BE_INFORMED."</font></td></tr>\n";
	$out .= "</table></div></div>\n";

	return $out;
}

/**
 * page_footer
 * Generates page footer.
 * @return Returns the HTML generated.
 */
function page_footer() {
	$out  ="</body>\n";
	$out .="</html>\n";
	return $out ;
}


//after user clicked submit
if (isset($_POST['email']) && isset($_POST['pwreq']) && isset($_POST['reason']) && isset($_POST['submit'])) {
	//Check given information with validator
	$email = $_POST['email'];
	$reason = $_POST['reason'];
	$pwreq = $_POST['pwreq'];

	$errors = validate_registration($email, $pwreq, $reason);

	if($errors['ok']) {
		db_add_new_account_request($email,$pwreq,$reason);
		print(page_header().account_created().page_footer());
	}
	else
		print(page_header().ds_registration_form($_SERVER["PHP_SELF"],"post",$errors,$email,$pwreq,$reason).page_footer());
}

//initial page with no errors set and empty fields
else {
	$errors = array("email" => false, "pwreq" => false, "reason" => false, "ok" => true);
	print(page_header().ds_registration_form($_SERVER["PHP_SELF"],"post",$errors, "","", "", "").page_footer());
}
?>
